/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg05_clientetcpsimples;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author aulas
 */
public class Tela extends javax.swing.JFrame {


    
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    public Tela(int lin, int col, int tam, int[][] matriz, Main main) {
        initComponents();
        this.main = main;
        this.matrizJogo = matriz;
        this.lin = lin;
        this.col = col;
        this.tamanho = tam;
        this.setSize(lin*(tam+2)-lin,col*(tam+2));
        telaPrincipal.setSize(lin*(tam+2)-lin,col*(tam+2));
        this.setResizable(false);
        this.setTitle("Jogo Legal");
        inicializaTela(lin, col);
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaPrincipal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        telaPrincipal.setName(""); // NOI18N

        jButton1.setText("jButton1");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaPrincipalLayout = new javax.swing.GroupLayout(telaPrincipal);
        telaPrincipal.setLayout(telaPrincipalLayout);
        telaPrincipalLayout.setHorizontalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPrincipalLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton1)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        telaPrincipalLayout.setVerticalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPrincipalLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jButton1)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    public void inicializaTela(int lin, int col){
        telaPrincipal.removeAll();
        tabuleiro = new JButton[lin][col];
        for(int i = 0;i<lin;i++){
            for(int j = 0;j<col;j++) {
                JButton jb = new JButton();
                telaPrincipal.add(jb);
                tabuleiro[i][j] = jb;
                jb.setBounds(i * tamanho, j * tamanho, tamanho, tamanho);
                //jb.setBorderPainted(false);
                //javax.swing.border.Border vazia = BorderFactory.createEmptyBorder();
                //javax.swing.border.Border vazia = BorderFactory.createLineBorder(Color.yellow, 1);
                //jb.setBorder(vazia);
                jb.addKeyListener(new KeyAdapter(){
                    public void keyPressed(KeyEvent ke) {
                        try {
                            main.enviarMensagem(ke.getKeyCode());
                        } catch (IOException ex) {
                            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
            }
        }
        //desenhaTela();
    }
    
    public void desenhaTela(int[][] matrizJogo) {
        JButton jb;
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                jb = tabuleiro[i][j];
                if (matrizJogo[i][j] == 0) {
                    jb.setBackground(Color.white);
                    jb.setRequestFocusEnabled(false);
                } else if (matrizJogo[i][j] >= 10) {
                    jb.setBackground(Color.green);
                    jb.requestFocus();
                } else if (matrizJogo[i][j] == 2) {
                    jb.setBackground(Color.blue);
                    jb.setRequestFocusEnabled(false);
                }
            }

        }
        telaPrincipal.repaint();
    }
    
    int lin;
    int col;
    int tamanho;
    int[][] matrizJogo;
    JButton[][] tabuleiro;
    Main main;
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel telaPrincipal;
    // End of variables declaration//GEN-END:variables
}
